[FLINK-33164] Support write option sink.ignore-null-value
apache/flink-connector-hbase pull request #21
Opened 2023-09-27 07:18 UTC by Tan-JiaLiang

## What is the purpose of the change

Sometimes, user want to write data and ignore null value to achieve partial update. 

## Brief change log

  - *support write option sink.ignore-null-value*

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

This change is already covered by existing tests, such as
  - *org.apache.flink.connector.hbase1.HBaseDynamicTableFactoryTest#testSinkIgnoreNullValueOptions*
  - *org.apache.flink.connector.hbase2.HBaseDynamicTableFactoryTest#testSinkIgnoreNullValueOptions*
  - *org.apache.flink.connector.hbase.util.HBaseSerdeTest#writeIgnoreNullValueTest*

2023-09-27 17:38 UTC, ferenc-csaky requested changes
Thank you for your contribution! The proposal and the logic makes sense IMO. Added some comments.

2023-09-27 17:38 UTC, ferenc-csaky commented on flink-connector-hbase-1.4/src/main/java/org/apache/flink/connector/hbase1/HBase1DynamicTableFactory.java
> +import static org.apache.flink.connector.hbase.table.HBaseConnectorOptions.*;
I suggest to avoid wildard imports.

2023-09-27 17:38 UTC, ferenc-csaky commented on flink-connector-hbase-1.4/src/test/java/org/apache/flink/connector/hbase1/HBaseDynamicTableFactoryTest.java
> +        assertEquals(expected.isIgnoreNullValue(), actual.isIgnoreNullValue());
I think instantiating a dummy expected object can be avoided, we can simply use `assertThat(actual.isIgnoreNullValue()).isTrue()`.

2023-09-27 17:38 UTC, ferenc-csaky commented on flink-connector-hbase-2.2/src/main/java/org/apache/flink/connector/hbase2/HBase2DynamicTableFactory.java
> +import static org.apache.flink.connector.hbase.table.HBaseConnectorOptions.*;
I suggest to avoid wildard imports.

2023-09-27 17:38 UTC, ferenc-csaky commented on flink-connector-hbase-2.2/src/test/java/org/apache/flink/connector/hbase2/HBaseDynamicTableFactoryTest.java
> +        assertEquals(expected.isIgnoreNullValue(), actual.isIgnoreNullValue());
I think instantiating a dummy expected object can be avoided, we can simply use `assertThat(actual.isIgnoreNullValue()).isTrue()`.

2023-09-27 17:38 UTC, ferenc-csaky commented on flink-connector-hbase-base/src/main/java/org/apache/flink/connector/hbase/table/HBaseConnectorOptionsUtil.java
> +import static org.apache.flink.connector.hbase.table.HBaseConnectorOptions.*;
I suggest to avoid wildard imports.

2023-09-27 17:38 UTC, ferenc-csaky commented on flink-connector-hbase-base/src/test/java/org/apache/flink/connector/hbase/util/HBaseSerdeTest.java
> +        Assert.assertEquals(10, Bytes.toInt(m1.getRow()));
Pls. use `Assert4J`'s `assertThat` for all kinds of asserts. The community agreed that it should be the standard going forward as part of the [JUnit5 migration](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit#heading=h.n2pt1kpwyals). It is not applied completely to this repo yet, but IMO it makes sense to conform with that if we touch some tests.

2023-09-28 02:53 UTC, Tan-JiaLiang commented
@ferenc-csaky Thanks for the code review, very helpful suggestions. I have changed it, please have a look.

2023-09-29 02:31 UTC, ferenc-csaky approved these changes
LGTM!

2023-10-25 13:42 UTC, ferenc-csaky commented
I would cherry-pick the changes relevant of this PR against the current `main` into a new local branch and force push that  to this origin branch, cause right now it contains changes and commits it should not.

2023-10-26 06:14 UTC, Tan-JiaLiang commented
@ferenc-csaky I rebase the main branch and squash all my changes.

And one more question master. there will be multiple commits during code reviews, Should I squash all commit into one and apply force push to the origin? Or keep it and wait for the maintainer to squash and merge?

2023-10-26 12:27 UTC, ferenc-csaky commented
> @ferenc-csaky I rebase the main branch and squash all my changes.
> 
> And one more question master. there will be multiple commits during code reviews, Should I squash all commit into one and apply force push to the origin? Or keep it and wait for the maintainer to squash and merge?

I think you can follow whichever path is more comfortable for you and for the specific case at hand. If there are multiple commits in the PR the maintainer will squash it, no problem.

@MartijnVisser any thoughts on this?

2023-10-26 12:29 UTC, ferenc-csaky approved these changes
LGTM!

2023-10-26 12:42 UTC, MartijnVisser commented
It's recommended to have multiple commits in a lot of situations, see https://flink.apache.org/how-to-contribute/code-style-and-quality-pull-requests/ - We can squash before merging

2023-10-26 13:23 UTC, Tan-JiaLiang commented
@ferenc-csaky @MartijnVisser Thanks for the patience guide. Making sense to me.

2023-11-03 15:38 UTC, ferenc-csaky commented
@MartijnVisser this is also in a mergeable state I think.

2023-11-03 15:51 UTC, MartijnVisser approved these changes

2023-11-03 15:51 UTC, merged