[FLINK-34413] Remove HBase 1.x connector files and deps
apache/flink-connector-hbase pull request #42
Opened 2024-02-22 14:54 UTC by ferenc-csaky

Took the as minimum change as possible approach. Some pinned/excluded dependencies probably can be cleaned up, but I'd rather do that separately to not involve too many changes.

2024-02-22 14:55 UTC, ferenc-csaky commented
cc @MartijnVisser

2024-03-04 14:30 UTC, ferenc-csaky commented
@Tan-JiaLiang if you have some time can you PTAL?

2024-03-04 20:20 UTC, MartijnVisser requested changes
@ferenc-csaky I found one more inclusion of `hbase-1.4` but otherwise this looks good. If you can fix that, I'll merge it afterwards

2024-03-04 20:20 UTC, MartijnVisser commented on flink-connector-hbase-e2e-tests/pom.xml
>  							<artifactItems>
On line 60-65 we still have an inclusion of `flink-connector-hbase-1.4`

2024-03-04 20:20 UTC, MartijnVisser commented on flink-connector-hbase-e2e-tests/pom.xml
>  							<artifactItems>
See https://github.com/apache/flink-connector-hbase/blob/7c9bda056cdded30daf39ef564e7396e22981c02/flink-connector-hbase-e2e-tests/pom.xml#L60-L65

2024-03-06 03:45 UTC, Tan-JiaLiang requested changes
@ferenc-csaky Thanks for driving this, almost looks good, added a minor comment.

2024-03-06 03:45 UTC, Tan-JiaLiang commented on docs/content.zh/docs/connectors/table/hbase.md
`docs/data/hbase.yml` we still have an inclusion of hbase-1.4 on 21-22, See

https://github.com/apache/flink-connector-hbase/blob/91d166d8c7ffb21ae065fce92618ecac74b7f9e7/docs/data/hbase.yml#L19-L24

2024-03-06 06:43 UTC, Tan-JiaLiang commented on docs/content.zh/docs/connectors/table/hbase.md
@ferenc-csaky I think just remove lines 21-22 instead of the whole file, WDYT?

2024-03-06 12:38 UTC, ferenc-csaky commented on docs/content.zh/docs/connectors/table/hbase.md
I lamented on this a bit, I checked the `flink` and `flink-web` repos and did not find if this is shown anywhere. And after this point, there are no "variants" of the connector, so keeping the file does not really makes sense IMO. But I might be wrong or miss something.

@MartijnVisser any thought about this?

2024-03-06 13:33 UTC, MartijnVisser commented on docs/content.zh/docs/connectors/table/hbase.md
> And after this point, there are no "variants" of the connector, so keeping the file does not really makes sense IMO. But I might be wrong or miss something.

It must remain there, since it's used when generating the download links for the documentation

2024-03-06 13:34 UTC, MartijnVisser commented on docs/content.zh/docs/connectors/table/hbase.md
It was to be updated during the release, see for example the Kafka one https://github.com/apache/flink-connector-kafka/blob/v3.1/docs/data/kafka.yml

2024-03-06 13:44 UTC, ferenc-csaky commented on docs/content.zh/docs/connectors/table/hbase.md
Thanks both of you, corrected the file!

2024-03-06 19:06 UTC, MartijnVisser approved these changes
LGTM

2024-03-06 19:06 UTC, merged